
version: '3.8'

services:
  neo4j:
    image: neo4j:5.14
    container_name: graph-neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.meta.data
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data


  qdrant:
    image: qdrant/qdrant
    container_name: vector-qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  jupyter:
    image: jupyter/scipy-notebook
    container_name: rag-jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''
    env_file:
      - .env
    environment:
      - JUPYTER_ENABLE_LAB=yes

volumes:
  neo4j_data:
  qdrant_data:
